2023-05-27 13:26:51 [ERROR] django.request Internal Server Error: /articulo/articulo/
Traceback (most recent call last):
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1054, "Unknown column 'articulo_articulo.tipo_articulo_id' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/models/query.py", line 320, in __iter__
    self._fetch_all()
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/models/query.py", line 1507, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/models/query.py", line 57, in __iter__
    results = compiler.execute_sql(
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1361, in execute_sql
    cursor.execute(sql, params)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/backends/utils.py", line 103, in execute
    return super().execute(sql, params)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'articulo_articulo.tipo_articulo_id' in 'field list'")
2023-05-27 13:26:51 [ERROR] django.server "GET /articulo/articulo/ HTTP/1.1" 500 201804
2023-05-27 13:27:46 [ERROR] django.request Internal Server Error: /articulo/articulo/
Traceback (most recent call last):
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1054, "Unknown column 'articulo_articulo.tipo_articulo_id' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/models/query.py", line 320, in __iter__
    self._fetch_all()
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/models/query.py", line 1507, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/models/query.py", line 57, in __iter__
    results = compiler.execute_sql(
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1361, in execute_sql
    cursor.execute(sql, params)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/backends/utils.py", line 103, in execute
    return super().execute(sql, params)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'articulo_articulo.tipo_articulo_id' in 'field list'")
2023-05-27 13:27:46 [ERROR] django.server "GET /articulo/articulo/ HTTP/1.1" 500 201804
2023-05-27 13:28:01 [ERROR] django.request Internal Server Error: /tipo/tipo/
Traceback (most recent call last):
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.ProgrammingError: (1146, "Table 'inventario.articulo_tipo' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/models/query.py", line 320, in __iter__
    self._fetch_all()
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/models/query.py", line 1507, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/models/query.py", line 57, in __iter__
    results = compiler.execute_sql(
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1361, in execute_sql
    cursor.execute(sql, params)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/backends/utils.py", line 103, in execute
    return super().execute(sql, params)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'inventario.articulo_tipo' doesn't exist")
2023-05-27 13:28:01 [ERROR] django.server "GET /tipo/tipo/ HTTP/1.1" 500 196467
2023-05-27 13:30:11 [ERROR] django.request Internal Server Error: /tipo/tipo/
Traceback (most recent call last):
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.ProgrammingError: (1146, "Table 'inventario.articulo_tipo' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/rest_framework/serializers.py", line 212, in save
    self.instance = self.create(validated_data)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/rest_framework/serializers.py", line 962, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/models/query.py", line 514, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/models/base.py", line 806, in save
    self.save_base(
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/models/base.py", line 857, in save_base
    updated = self._save_table(
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/models/base.py", line 1000, in _save_table
    results = self._do_insert(
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/models/base.py", line 1041, in _do_insert
    return manager._insert(
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/models/query.py", line 1434, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1621, in execute_sql
    cursor.execute(sql, params)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/backends/utils.py", line 103, in execute
    return super().execute(sql, params)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'inventario.articulo_tipo' doesn't exist")
2023-05-27 13:30:11 [ERROR] django.server "POST /tipo/tipo/ HTTP/1.1" 500 226308
2023-05-27 13:45:59 [ERROR] django.request Internal Server Error: /articulo/articulo/
Traceback (most recent call last):
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1054, "Unknown column 'articulo_articulo.tipo_articulo_id' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/models/query.py", line 320, in __iter__
    self._fetch_all()
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/models/query.py", line 1507, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/models/query.py", line 57, in __iter__
    results = compiler.execute_sql(
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1361, in execute_sql
    cursor.execute(sql, params)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/backends/utils.py", line 103, in execute
    return super().execute(sql, params)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'articulo_articulo.tipo_articulo_id' in 'field list'")
2023-05-27 13:45:59 [ERROR] django.server "GET /articulo/articulo/ HTTP/1.1" 500 201804
2023-05-27 13:47:01 [ERROR] django.request Internal Server Error: /articulo/articulo/
Traceback (most recent call last):
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1054, "Unknown column 'tipo_articulo_id' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/rest_framework/serializers.py", line 212, in save
    self.instance = self.create(validated_data)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/rest_framework/serializers.py", line 962, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/models/query.py", line 514, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/models/base.py", line 806, in save
    self.save_base(
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/models/base.py", line 857, in save_base
    updated = self._save_table(
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/models/base.py", line 1000, in _save_table
    results = self._do_insert(
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/models/base.py", line 1041, in _do_insert
    return manager._insert(
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/models/query.py", line 1434, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1621, in execute_sql
    cursor.execute(sql, params)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/backends/utils.py", line 103, in execute
    return super().execute(sql, params)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'tipo_articulo_id' in 'field list'")
2023-05-27 13:47:01 [ERROR] django.server "POST /articulo/articulo/ HTTP/1.1" 500 241154
2023-09-03 00:43:14 [ERROR] django.request Internal Server Error: /articulo/articulo/
Traceback (most recent call last):
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.DataError: (1406, "Data too long for column 'descripcion' at row 1")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/rest_framework/serializers.py", line 212, in save
    self.instance = self.create(validated_data)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/rest_framework/serializers.py", line 962, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/models/query.py", line 514, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/models/base.py", line 806, in save
    self.save_base(
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/models/base.py", line 857, in save_base
    updated = self._save_table(
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/models/base.py", line 1000, in _save_table
    results = self._do_insert(
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/models/base.py", line 1041, in _do_insert
    return manager._insert(
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/models/query.py", line 1434, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1621, in execute_sql
    cursor.execute(sql, params)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/backends/utils.py", line 103, in execute
    return super().execute(sql, params)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/vlopez/Documents/Desarrollo/inventario-svelte/entorno/lib/python3.9/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.DataError: (1406, "Data too long for column 'descripcion' at row 1")
2023-09-03 00:43:14 [ERROR] django.server "POST /articulo/articulo/ HTTP/1.1" 500 243964
